version: "3.7"

services:
  code-server:
    image: hugo-coder-server
    container_name: hugo-coder-server
    build:
      context: .
    tty: true
    environment:
      CODESERVER_PASSWORD: $CODESERVER_PASSWORD
      GITHUB_USERNAME: $GITHUB_USERNAME
      GITHUB_TOKEN: $GITHUB_TOKEN      
      GIT_AUTHOR_NAME: $GIT_USERNAME
      GIT_COMMITTER_NAME: $GIT_USERNAME
      EMAIL: $GIT_USER_EMAIL
    working_dir: /home/coder/blog
    volumes:
      - '.:/home/coder/blog:cached'
    ports:
      - '8080:8080'
      - '1313:1313'
