name: biuld_and_publish
on:
  push:
    branches:
      - source
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Publish
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.78.0'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        if: ${{ github.event_name == 'push' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
