name: update_docker_image
on:
  push:
    branches:
      - source
    paths:
      - 'Dockerfile'
      - 'docker/**'

env:
  DOCKER_BUILDKIT: 1
  IMAGE_NAME: hugo-code-server
  IMAGE_TAG: latest

jobs:
  test:
    runs-on: ubuntu-latest
    name: Update hugo-code-server image
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0

      - name: Login GitHub Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Image
        run: docker build . --tag ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:${IMAGE_TAG}

      - name: Push Image
        run: docker push ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}:${IMAGE_TAG}
